IMAGE_NAME=yt-application

# Docker container name
CONTAINER_NAME=mirja_galib

# Dockerfile location
DOCKERFILE=Dockerfile

# Build Docker image
build:
	docker build -t $(IMAGE_NAME) .

# Run Docker container
run:
	docker run -d -p3000:3000 $(IMAGE_NAME)

# Stop Docker container
stop:
	docker container stop $(CONTAINER_NAME)

# Remove Docker container
rm:
	docker container rm $(CONTAINER_NAME)

# Build and run Docker container
all: build run
